Consolidate system determination functions

diff --git a/system/Build_VM b/system/Build_VM
--- a/system/Build_VM
+++ b/system/Build_VM
@@ -14,28 +14,51 @@
 : ${ZIPROOT:=${hosthome}/software/zip}
 export SCMROOT USRLOCAL ZIPROOT
 
-# Define a function to install packages on either debian or Fedora.
-function install_package() {
-  if [[ -x /usr/bin/dnf ]]; then
-    pm="dnf --assumeyes"
-  elif [[ -x /usr/bin/apt-get ]]; then
-    pm="apt-get --yes"
+# Define helper functions to identify the type of the underlying OS.
+function debian-p() {
+  [[ -x /usr/bin/apt-get ]]
+}
+function fedora-p() {
+  [[ -x /usr/bin/dnf ]]
+}
+function os-type() {
+  if debian-p; then
+    echo "debian"
+  elif fedora-p; then
+    echo "Fedora"
   else
-    echo Neither dnf nor apt-get was found to install packages.  Exiting. >/dev/tty
-    exit 3
+    echo "Not a supported OS type." >/dev/tty
+    return 1
   fi
+  return 0
+}
+function package_manager() {
+  if debian-p; then
+    echo "apt-get --yes"
+  elif fedora-p; then
+    echo "dnf --assumeyes"
+  else
+    echo "Not a supported OS type." >/dev/tty
+    return 1
+  fi
+  return 0
+}
+
+# Define a platform-agnostic function to install packages.
+function install_package() {
+  # Package_manager has already reported this error.
+  pm=$(package_manager) || exit $?
   sudo ${pm} install $*
 }
 
-# Define a function to upgrade packages on either debian or Fedora.
+# Define a platform-agnostic function to upgrade packages.
 function upgrade_packages() {
-  if [[ -x /usr/bin/dnf ]]; then
-    sudo dnf --assumeyes upgrade
-  elif [[ -x /usr/bin/apt-get ]]; then
-    sudo apt-get --yes update && sudo apt-get --yes upgrade
-  else
-    echo Neither dnf nor apt-get was found to upgrade packages.  Exiting. >/dev/tty
-    exit 3
+  # Package_manager has already reported this error.
+  pm=$(package_manager) || exit $?
+  if fedora-p; then
+    sudo $pm upgrade
+  elif debian-p; then
+    sudo $pm update && sudo $pm upgrade
   fi
 }
 
@@ -62,7 +85,7 @@ if ! groups acs | grep vboxsf >/dev/null; then
   fi
 
   if [[ ! -x /mnt/VBoxLinuxAdditions.run ]]; then
-    echo "Cannot find /mnt/VBoxLinuxAdditions.run, exiting." >/dev/tty
+    echo "Cannot find /mnt/VBoxLinuxAdditions.run.  Exiting." >/dev/tty
     exit 2
   fi
 
@@ -79,15 +102,6 @@ if ! groups acs | grep vboxsf >/dev/null; then
   sudo reboot
 fi
 
-if [[ -x /usr/bin/apt-get ]]; then
-  variable_source=${variable_source}/debian
-elif [[ -x /usr/bin/dnf ]]; then
-  variable_source=${variable_source}/Fedora
-else
-  echo Cannot ascertain whether this system is debian or Fedora >/dev/tty
-  exit 1
-fi
-
 # Configure my home directory.
 mkdir -p ${SCMROOT}/hgroot
 tar cf - -C ${hosthome}/scmroot/hgroot acsfiles | tar xf - -C ${SCMROOT}/hgroot
@@ -97,6 +111,27 @@ ln -s hgroot/acsfiles hgroot/acsfiles/binfiles hgroot/acsfiles/rcfiles ${SCMROOT
   ${SCMROOT}/binfiles/LinkStartupFiles
   mkdir .hist
   tar xf ${ZIPROOT}/wp.tar
+  cat >bin/xfce-autostart <<EOF
+#!/bin/bash
+
+# Script to start up an XFCE session.
+
+: \${USRLOCAL:=/opt}
+PATH=\$HOME/bin:\$USRLOCAL/bin:$PATH
+
+xfce4-terminal --geometry 90x60-1+1 &
+emacs &
+
+conky --pause=5 &
+
+# Local Variables:
+# mode: shell-script
+# sh-basic-offset: 2
+# sh-indentation: 2
+# indent-tabs-mode: nil
+# End:
+EOF
+  chmod 755 bin/xfce-autostart
 )
 
 # Make the USRLOCAL hierarchy.
@@ -115,6 +150,10 @@ else
   sudo mv /etc/z* /etc/ZSH-dist
 fi
 install_package git i3 mercurial
+
+# The error has already been reported if we're not running
+# on debian or Fedora, so the exit call is appropriate.
+variable_source=${variable_source}/$(os-type) || exit $?
 
 . ${variable_source}/Microsoft_fonts
 
@@ -189,13 +228,12 @@ mk-${pname}
 link_latest ${pname} ${pname}-$(today)
 
 echo "
-*********************************
+*************************************
 Remember to:
-  1. Turn off screensaver.
-  2. Create ~/bin/xfce-autostart.
-  3. Modify session start-up.
-  4. Tune up xfce window manager.
-*********************************
+  1. Turn off the screensaver.
+  2. Modify session start-up.
+  3. Tune up the xfce window manager.
+*************************************
 "
 
 # Local Variables:
